# Generated by Django 5.2.16
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("accounts", "0002_artistprofile")]
    operations = [migrations.CreateModel(
        name="Notification",
        fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ("type", models.CharField(choices=[("new_release", "New release"), ("subscription_expiry", "Subscription expiry"), ("artist_approved", "Artist approved"), ("artist_rejected", "Artist rejected"), ("ticket_update", "Ticket update"), ("monthly_financial", "Monthly financial"), ("announcement", "Announcement")], db_index=True, max_length=32)),
            ("title", models.CharField(max_length=200)),
            ("message", models.TextField(max_length=2000)),
            ("link", models.CharField(blank=True, max_length=500)),
            ("read_at", models.DateTimeField(blank=True, db_index=True, null=True)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to=settings.AUTH_USER_MODEL)),
        ],
        options={"ordering": ("-created_at",), "indexes": [models.Index(fields=["user", "read_at", "created_at"], name="notif_user_read_time_idx")]},
    )]

