# Generated by Django 5.2.16 on 2026-08-13 13:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_audio_file_stream'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyPlayed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_played_by', to='music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_played', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-played_at',),
                'indexes': [models.Index(fields=['user', 'played_at'], name='music_recent_user_time_idx')],
            },
        ),
    ]
