# Generated by Django 5.2.16 on 2026-08-15 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_existing_artist_profiles(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    ArtistProfile = apps.get_model("accounts", "ArtistProfile")
    ArtistApplication = apps.get_model("accounts", "ArtistApplication")
    names = dict(
        ArtistApplication.objects.filter(status="approved").values_list("user_id", "artist_name")
    )
    for user in User.objects.filter(role="artist", artist_verified=True):
        ArtistProfile.objects.get_or_create(
            user_id=user.pk,
            defaults={"stage_name": names.get(user.pk) or user.display_name or user.username},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=150)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('payout_currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'artist'}, on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_existing_artist_profiles, migrations.RunPython.noop),
    ]
