import type { Song, Album, Playlist } from "@/types/music";

export const MOCK_SONGS: Song[] = [
  {
    id: "s1",
    title: "Midnight Drive",
    artistName: "Bob Artist",
    albumId: "a1",
    durationSec: 214,
    coverColor: "#1a1a2e",
    playCount: 15420,
  },
  {
    id: "s2",
    title: "Neon Lights",
    artistName: "Bob Artist",
    albumId: "a1",
    durationSec: 187,
    coverColor: "#1a1a2e",
    playCount: 12300,
  },
  {
    id: "s3",
    title: "Sunrise Melody",
    artistName: "Bob Artist",
    albumId: "a1",
    durationSec: 243,
    coverColor: "#1a1a2e",
    playCount: 9800,
  },
  {
    id: "s4",
    title: "Echoes",
    artistName: "Luna Wave",
    albumId: "a2",
    durationSec: 198,
    coverColor: "#16213e",
    playCount: 22100,
  },
  {
    id: "s5",
    title: "Falling Stars",
    artistName: "Luna Wave",
    albumId: "a2",
    durationSec: 226,
    coverColor: "#16213e",
    playCount: 18700,
  },
  {
    id: "s6",
    title: "Ocean Breeze",
    artistName: "Luna Wave",
    albumId: "a2",
    durationSec: 205,
    coverColor: "#16213e",
    playCount: 14500,
  },
  {
    id: "s7",
    title: "Velvet Sky",
    artistName: "Nova Drift",
    albumId: "a3",
    durationSec: 176,
    coverColor: "#0f3460",
    playCount: 8900,
  },
  {
    id: "s8",
    title: "Crystal Rain",
    artistName: "Nova Drift",
    albumId: "a4",
    durationSec: 231,
    coverColor: "#533483",
    playCount: 6200,
  },
];

export const MOCK_ALBUMS: Album[] = [
  {
    id: "a1",
    title: "After Hours",
    artistName: "Bob Artist",
    coverColor: "#1a1a2e",
    releaseDate: "2026-06-15",
    songIds: ["s1", "s2", "s3"],
    isEarlyAccess: false,
  },
  {
    id: "a2",
    title: "Dreamscape",
    artistName: "Luna Wave",
    coverColor: "#16213e",
    releaseDate: "2026-06-20",
    songIds: ["s4", "s5", "s6"],
    isEarlyAccess: false,
  },
  {
    id: "a3",
    title: "Horizons",
    artistName: "Nova Drift",
    coverColor: "#0f3460",
    releaseDate: "2026-06-25",
    songIds: ["s7"],
    isEarlyAccess: true,
  },
  {
    id: "a4",
    title: "Prism",
    artistName: "Nova Drift",
    coverColor: "#533483",
    releaseDate: "2026-06-28",
    songIds: ["s8"],
    isEarlyAccess: true,
  },
];

export const MOCK_PLAYLISTS: Playlist[] = [
  {
    id: "p1",
    title: "Late Night Vibes",
    coverColor: "#1b1b2f",
    songIds: ["s1", "s4", "s7"],
    createdBy: "u1",
    description: "Chill tracks for late nights",
  },
  {
    id: "p2",
    title: "Morning Energy",
    coverColor: "#2d132c",
    songIds: ["s2", "s5", "s8"],
    createdBy: "u1",
    description: "Start your day right",
  },
  {
    id: "p3",
    title: "Focus Mode",
    coverColor: "#1a1a40",
    songIds: ["s3", "s6"],
    createdBy: "u2",
    description: "Deep focus instrumental vibes",
  },
  {
    id: "p4",
    title: "Top Hits 2026",
    coverColor: "#3c1642",
    songIds: ["s1", "s4", "s5", "s7", "s8"],
    createdBy: "u3",
    description: "The biggest tracks of the year",
  },
];
