import type { CurrentSubscription, PlanTier, User } from "@/types/user";

function subscription(plan: PlanTier, expiresAt: string | null): CurrentSubscription {
  return {
    plan,
    status: "active",
    startsAt: "2026-01-01T00:00:00Z",
    expiresAt,
    limits: {
      dailyStreamLimit: plan === "free" ? 60 : null,
      maxPlaylists: plan === "free" ? 6 : plan === "silver" ? 100 : null,
      profileImageAllowed: plan !== "free",
      downloadAllowed: plan !== "free",
      earlyAccessAllowed: plan === "gold",
      statisticsAllowed: plan === "gold",
    },
  };
}

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    email: "mahyar@example.com",
    displayName: "Mahyar Listener",
    username: "mahyar_l",
    role: "listener",
    birthDate: "1995-03-15",
    gender: "female",
    avatarUrl: null,
    bio: "",
    artistVerified: false,
    followersCount: 1,
    followingCount: 1,
    streamsToday: 0,
    preferences: {
      newReleasesFromFollowed: true,
      subscriptionExpiry: true,
      ticketUpdates: false,
      soundEnabled: true,
      language: "en",
    },
    subscription: subscription("free", null),
  },
  {
    id: "u2",
    email: "ali@example.com",
    displayName: "Ali Artist",
    username: "ali_a",
    role: "artist",
    birthDate: "1990-07-22",
    gender: "male",
    avatarUrl: null,
    bio: "Indie musician from Seattle",
    artistVerified: true,
    followersCount: 2,
    followingCount: 1,
    streamsToday: 0,
    preferences: {
      newReleasesFromFollowed: true,
      subscriptionExpiry: true,
      ticketUpdates: true,
      soundEnabled: true,
      language: "en",
    },
    subscription: subscription("silver", "2026-07-25"),
  },
  {
    id: "u3",
    email: "hasan@example.com",
    displayName: "Hasan Admin",
    username: "hasan_admin",
    role: "admin",
    birthDate: "1988-01-05",
    gender: "other",
    avatarUrl: null,
    bio: "",
    artistVerified: false,
    followersCount: 0,
    followingCount: 2,
    streamsToday: 0,
    preferences: {
      newReleasesFromFollowed: true,
      subscriptionExpiry: true,
      ticketUpdates: true,
      soundEnabled: false,
      language: "fa",
    },
    subscription: subscription("gold", "2026-12-31"),
  },
  {
    id: "u4",
    email: "parsa@example.com",
    displayName: "Parsa Support",
    username: "parsa_s",
    role: "support",
    birthDate: "1992-11-30",
    gender: "male",
    avatarUrl: null,
    bio: "",
    artistVerified: false,
    followersCount: 0,
    followingCount: 0,
    streamsToday: 0,
    preferences: {
      newReleasesFromFollowed: false,
      subscriptionExpiry: true,
      ticketUpdates: true,
      soundEnabled: true,
      language: "en",
    },
    subscription: subscription("free", null),
  },
];
