import type { User } from "@/types/user";

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    email: "alice@example.com",
    passwordHash: "$2b$10$mockhashalice",
    displayName: "Alice Listener",
    username: "alice_l",
    role: "listener",
    birthDate: "1995-03-15",
    gender: "female",
    avatarUrl: null,
    planTier: "free",
    planRenewsAt: null,
    followers: ["u2"],
    following: ["u2"],
    notificationLimits: {
      newReleasesFromFollowed: true,
      subscriptionExpiry: true,
      ticketUpdates: false,
    },
    soundEnabled: true,
    language: "en",
    createdAt: "2025-01-10T00:00:00Z",
  },
  {
    id: "u2",
    email: "bob@example.com",
    passwordHash: "$2b$10$mockhashbob",
    displayName: "Bob Artist",
    username: "bob_a",
    role: "artist",
    birthDate: "1990-07-22",
    gender: "male",
    avatarUrl: null,
    bio: "Indie musician from Seattle",
    planTier: "silver",
    planRenewsAt: "2026-07-25",
    followers: ["u1", "u3"],
    following: ["u1"],
    notificationLimits: {
      newReleasesFromFollowed: true,
      subscriptionExpiry: true,
      ticketUpdates: true,
    },
    soundEnabled: true,
    language: "en",
    createdAt: "2024-11-01T00:00:00Z",
  },
  {
    id: "u3",
    email: "carol@example.com",
    passwordHash: "$2b$10$mockhashcarol",
    displayName: "Carol Admin",
    username: "carol_admin",
    role: "admin",
    birthDate: "1988-01-05",
    gender: "other",
    avatarUrl: null,
    planTier: "gold",
    planRenewsAt: "2026-12-31",
    followers: [],
    following: ["u1", "u2"],
    notificationLimits: {
      newReleasesFromFollowed: true,
      subscriptionExpiry: true,
      ticketUpdates: true,
    },
    soundEnabled: false,
    language: "fa",
    createdAt: "2024-06-15T00:00:00Z",
  },
  {
    id: "u4",
    email: "dave@example.com",
    passwordHash: "$2b$10$mockhashdave",
    displayName: "Dave Support",
    username: "dave_s",
    role: "support",
    birthDate: "1992-11-30",
    gender: "male",
    avatarUrl: null,
    planTier: "free",
    planRenewsAt: null,
    followers: [],
    following: [],
    notificationLimits: {
      newReleasesFromFollowed: false,
      subscriptionExpiry: true,
      ticketUpdates: true,
    },
    soundEnabled: true,
    language: "en",
    createdAt: "2025-03-20T00:00:00Z",
  },
];
