# Generated by Django 5.2.16
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("accounts", "0002_artistprofile"), ("music", "0003_recentlyplayed")]
    operations = [migrations.CreateModel(
        name="ArtistPayout",
        fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ("month", models.DateField(help_text="First day of the reporting month.")),
            ("total_streams", models.PositiveIntegerField(default=0)),
            ("rate_per_stream", models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ("amount", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ("currency", models.CharField(default="USD", max_length=3)),
            ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("paid", "Paid"), ("disputed", "Disputed")], db_index=True, default="pending", max_length=16)),
            ("provider_reference", models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ("generated_at", models.DateTimeField(auto_now_add=True)),
            ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ("paid_at", models.DateTimeField(blank=True, null=True)),
            ("artist", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="artist_payouts", to=settings.AUTH_USER_MODEL)),
            ("generated_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="generated_payouts", to=settings.AUTH_USER_MODEL)),
            ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reviewed_payouts", to=settings.AUTH_USER_MODEL)),
        ],
        options={"ordering": ("-month", "artist__display_name"), "indexes": [models.Index(fields=["month", "status"], name="payments_month_status_idx")], "constraints": [models.UniqueConstraint(fields=("artist", "month"), name="payments_artist_month_unique")]},
    )]
